### ISSUE TITLE
Process only storage-related events

### ISSUE THREAD

**Issue by kdembler** [Joystream/storage-squid#2]
Currently I think all the mappings from Orion were brought over. While this is still a great improvement over using QN which indexes almost everything, this squid should be good with indexing only storage related events, ignoring content and memberships completely for now. On top of storage directly, we may need DWG/SWG associated events so that bucket assignments, etc are available

**Comment by zeeshanakram3** [comment]
> On top of storage directly, we may need DWG/SWG associated events so that bucket assignments, etc are available

Can you please elaborate on this?

**Comment by zeeshanakram3** [comment]
Addressed in #4
